name: PC Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  IceSDK:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Build Files
        run: .\tools\win\gn.exe gen out

      - name: Build IceSDK
        run: .\tools\win\ninja.exe -C out
      
      - name: Execute Tests
        run: |
          cd out
          .\TestIceSDK
