name: PC Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  IceSDK:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Build Files
        run: |
          mkdir .\build\
          cd .\build\


          cmake .. -DICESDK_BUILD_TESTS=ON
        shell: pwsh

      - name: Build IceSDK
        run: cmake --build build --config Release --target ALL_BUILD -- /maxcpucount:14

      - name: Execute Tests
        run: .\build\bin\TestIceSDK
