name: PC Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  IceSDK:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Build Files
        run: |
          mkdir .\build\
          cd .\build\

          cmake .. -G Ninja -DICESDK_BUILD_TESTS=ON
        shell: pwsh

      - name: Build IceSDK
        run: .\tools\win\ninja.exe -C build
      
      - name: Execute Tests
        run: .\build\TestIceSDK
