name: Win32 Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BareBones:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Required Toolchain
        run: |
          git submodule update --init --recursive
          
          .\third-party\emsdk\emsdk.ps1 install latest
          .\third-party\emsdk\emsdk.ps1 activate latest
        shell: pwsh

      - name: Generate Build Files
        run: |
          .\third-party\emsdk\emsdk_env.ps1

          mkdir .\out\
          Copy-Item .\.ide\GN\win\emscripten\args.gn -Destination .\out\args.gn
          
          .\tools\win\gn.exe gen out
        shell: pwsh

      - name: Build BareBones
        run: |
          .\third-party\emsdk\emsdk_env.ps1
          .\tools\win\ninja.exe -C out BareBones
        shell: pwsh
