name: Win32 Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BareBones:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Required Toolchain
        run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          
          .\emsdk\emsdk.ps1 install latest
          .\emsdk\emsdk.ps1 activate latest
        shell: pwsh

      - name: Generate Build Files
        run: |
          .\emsdk\emsdk_env.ps1

          mkdir .\out\
          Copy-Item .\.github\emscripten\args.gn -Destination .\out\args.gn

          .\tools\win\gn.exe gen out
        shell: pwsh

      - name: Build BareBones
        run: |
          .\emsdk\emsdk_env.ps1
          .\tools\win\ninja.exe -C out BareBones
        shell: pwsh
